Traceback (most recent call last):
  File "/home/upasana/anaconda3/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/upasana/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/upasana/anaconda3/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/upasana/anaconda3/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/upasana/anaconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/upasana/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/upasana/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/upasana/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#constants
eta_t = 0.5 # Î·_T estimated as Î·_t because Î· is microscopic
h_0=1 #typical disk scale in Mpc
t_0 = (h_0**2)/eta_t
Omega = 1/t_0 #Omega has units of 1/t0
Alpha = h/t_0 #Alpha has units of h0/t0
q = 1
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 6[0m
[1;32m      4[0m t_0 [38;5;241m=[39m (h_0[38;5;241m*[39m[38;5;241m*[39m[38;5;241m2[39m)[38;5;241m/[39meta_t
[1;32m      5[0m Omega [38;5;241m=[39m [38;5;241m1[39m[38;5;241m/[39mt_0 [38;5;66;03m#Omega has units of 1/t0[39;00m
[0;32m----> 6[0m Alpha [38;5;241m=[39m [43mh[49m[38;5;241m/[39mt_0 [38;5;66;03m#Alpha has units of h0/t0[39;00m
[1;32m      7[0m q [38;5;241m=[39m [38;5;241m1[39m

[0;31mNameError[0m: name 'h' is not defined
NameError: name 'h' is not defined

